UPDATE game_event SET description='仲夏焰火节 ' WHERE entry=1;
UPDATE game_event SET description='冬幕节 ' WHERE entry=2;
UPDATE game_event SET description='暗月马戏团（泰罗卡森林） ' WHERE entry=3;
UPDATE game_event SET description='暗月马戏团（艾尔文森林） ' WHERE entry=4;
UPDATE game_event SET description='暗月马戏团（莫高雷） ' WHERE entry=5;
UPDATE game_event SET description='除夕' WHERE entry=6;
UPDATE game_event SET description='农历节庆' WHERE entry=7;
UPDATE game_event SET description='爱意弥漫的天空 ' WHERE entry=8;
UPDATE game_event SET description='贵族花园 ' WHERE entry=9;
UPDATE game_event SET description='儿童周 ' WHERE entry=10;
UPDATE game_event SET description='收获节 ' WHERE entry=11;
UPDATE game_event SET description='万圣节 ' WHERE entry=12;
UPDATE game_event SET description='安其拉之战 ' WHERE entry=22;
UPDATE game_event SET description='天灾入侵 ' WHERE entry=17;
UPDATE game_event SET description='元素生物入侵 ' WHERE entry=13;
UPDATE game_event SET description='钓鱼比赛 ' WHERE entry=14;
UPDATE game_event SET description='古拉巴什竞技场战斗 ' WHERE entry=16;
UPDATE game_event SET description='钓鱼比赛 ' WHERE entry=15;
UPDATE game_event SET description='战斗的召唤：奥特兰克山谷 ' WHERE entry=18;
UPDATE game_event SET description='战斗的召唤：战歌峡谷 ' WHERE entry=19;
UPDATE game_event SET description='战斗的召唤：阿拉希盆地 ' WHERE entry=20;
UPDATE game_event SET description='战斗的召唤：风暴之眼 ' WHERE entry=21;
UPDATE game_event SET description='奥格瑞玛狼群进攻 ( 队伍一 ) ' WHERE entry=23;
UPDATE game_event SET description='奥格瑞玛狼群进攻 ( 队伍二 ) ' WHERE entry=24;
UPDATE game_event SET description='奥格瑞玛防守战斗 ' WHERE entry=25;
UPDATE game_event SET description='金亚莱之主, 库图比萨 ' WHERE entry=27;
UPDATE game_event SET description='亡灵军队进攻暴风城 (亡灵进攻) ' WHERE entry=28;
UPDATE game_event SET description='夜幕 ' WHERE entry=29;
UPDATE game_event SET description='战斗的召唤：远古海滩 ' WHERE entry=30;
UPDATE game_event SET description='达拉然 - 冠军邀请' WHERE entry=31;
UPDATE game_event SET description='海盗节日 ' WHERE entry=32;
UPDATE game_event SET description='金亚莱之主, 加瓦尼尔 ' WHERE entry=33;
UPDATE game_event SET description='L70ETC 音乐会 ' WHERE entry=34;
UPDATE game_event SET description='钓鱼任务 ' WHERE entry=35;
UPDATE game_event SET description='疯狂之缘，哈拉扎丝 ' WHERE entry=36;
UPDATE game_event SET description='疯狂之缘，瑞纳卡奇 ' WHERE entry=37;
UPDATE game_event SET description='疯狂之缘，乌苏雷 ' WHERE entry=38;
UPDATE game_event SET description='金亚莱之主, 『疯子』丘洛 ' WHERE entry=39;
UPDATE game_event SET description='亡者之日 ' WHERE entry=40;
UPDATE game_event SET description='朝圣者的恩赐 ' WHERE entry=41;
UPDATE game_event SET description='战斗的召唤：征服之岛 ' WHERE entry=42;
UPDATE game_event SET description='落锤镇战斗 ' WHERE entry=43;
UPDATE game_event SET description='萨尔玛恶魔攻击 ' WHERE entry=44;
UPDATE game_event SET description='卡鲁亚克钓鱼大赛 ' WHERE entry=45;
UPDATE game_event SET description='札拉赞恩的死亡 ' WHERE entry=46;
UPDATE game_event SET description='行动：诺莫瑞根 ' WHERE entry=47;
UPDATE game_event SET description='三月 ' WHERE entry=52;
UPDATE game_event SET description='二月 ' WHERE entry=51;
UPDATE game_event SET description='元素生物 & 暮光之锤的入侵 ' WHERE entry=48;
UPDATE game_event SET description='冬幕节:礼物 ' WHERE entry=49;
UPDATE game_event SET description='四月 ' WHERE entry=53;
UPDATE game_event SET description='六月 ' WHERE entry=55;
UPDATE game_event SET description='七月 ' WHERE entry=56;
UPDATE game_event SET description='八月 ' WHERE entry=57;
UPDATE game_event SET description='九月 ' WHERE entry=58;
UPDATE game_event SET description='十月 ' WHERE entry=59;
UPDATE game_event SET description='十一月 ' WHERE entry=60;
UPDATE game_event SET description='五月 ' WHERE entry=54;
UPDATE game_event SET description='一月 ' WHERE entry=50;
UPDATE game_event SET description='十二月 ' WHERE entry=61;
UPDATE game_event SET description='世界的尽头旅店：佩里·盖特的公告 ' WHERE entry=62;
UPDATE game_event SET description='世界的尽头旅店：佩里·盖特的表演 ' WHERE entry=63;
UPDATE game_event SET description='冬季钓鱼大赛 ' WHERE entry=64;
UPDATE game_event SET description='Beer of the Month - Januar' WHERE entry=86;
UPDATE game_event SET description='Beer of the Month - Februar' WHERE entry=87;
UPDATE game_event SET description='Beer of the Month - March' WHERE entry=88;
UPDATE game_event SET description='Beer of the Month - April' WHERE entry=89;
UPDATE game_event SET description='Beer of the Month - May' WHERE entry=90;
UPDATE game_event SET description='Beer of the Month - June' WHERE entry=91;
UPDATE game_event SET description='Beer of the Month - July' WHERE entry=92;
UPDATE game_event SET description='Beer of the Month - August' WHERE entry=93;
UPDATE game_event SET description='Pilgrim''s Bounty' WHERE entry=125;
UPDATE game_event SET description='Beer of the Month - September' WHERE entry=94;
UPDATE game_event SET description='Daily Magisters Terrace' WHERE entry=123;
UPDATE game_event SET description='Beer of the Month - Oktober' WHERE entry=95;
UPDATE game_event SET description='Beer of the Month - November' WHERE entry=96;
UPDATE game_event SET description='Brewfest - Attack of The Dark Iron Dwarfs' WHERE entry=85;
UPDATE game_event SET description='Beer of the Month - December' WHERE entry=97;
UPDATE game_event SET description='Pilgrim''s Bounty' WHERE entry=70;

