update mangos_string set content_default='您应该选择角色或生物。' where entry=1;
update mangos_string set content_default='您应该选择一个生物。' where entry=2;
update mangos_string set content_default='|cffff 0000[ 系统消息]: %s| r' where entry=3;
update mangos_string set content_default='|cffff 0000[ 活动消息]: %s| r' where entry=4;
update mangos_string set content_default='这里没有此指令的帮助信息' where entry=5;
update mangos_string set content_default='这个指令不存在' where entry=6;
update mangos_string set content_default='这里没有此类子指令' where entry=7;
update mangos_string set content_default='指令%s有子指令:' where entry=8;
update mangos_string set content_default='你可以使用的指令有:' where entry=9;
update mangos_string set content_default='指令语法格式错误。' where entry=10;
update mangos_string set content_default='你的账号级别是: %i' where entry=11;
update mangos_string set content_default='在线人数: %u(最多时: %u) 排队人数: %u(最多时: %u)' where entry=12;
update mangos_string set content_default='服务器正常运行时间: %s' where entry=13;
update mangos_string set content_default='系统帮助：玩家数据存储成功。' where entry=14;
update mangos_string set content_default='系统帮助：存储所有玩家数据成功。' where entry=15;
update mangos_string set content_default='系统帮助：在此服务器上有以下在线的ＧＭ:' where entry=16;
update mangos_string set content_default='系统帮助：当前没有 G M 登录在这台服务器上。' where entry=17;
update mangos_string set content_default='系统帮助：当处于飞行中时，不能这样做。' where entry=18;
update mangos_string set content_default='系统帮助：目标在飞行中，你不能这样做。' where entry=20;
update mangos_string set content_default='系统帮助：在战场里不能这样做。' where entry=19;
update mangos_string set content_default='%s 正在飞行中，指令无效。' where entry=21;
update mangos_string set content_default='系统帮助：你没有在骑乘状态，因此你不能卸下骑乘。' where entry=22;
update mangos_string set content_default='系统帮助：在战斗中不能这样做。' where entry=23;
update mangos_string set content_default='系统帮助：您最近已经使用过它。' where entry=24;
update mangos_string set content_default='系统帮助：您的口令不能设置超过 16 个字符长度 (客户极限), 口令没被改变' where entry=25;
update mangos_string set content_default='系统帮助：口令已经修改。' where entry=26;
update mangos_string set content_default='口令错误' where entry=27;
update mangos_string set content_default='系统帮助：你的账号现在被锁定。' where entry=28;
update mangos_string set content_default='系统帮助：你的账号已取消锁定。' where entry=29;
update mangos_string set content_default=', 等级' where entry=30;
update mangos_string set content_default='[已知的]' where entry=31;
update mangos_string set content_default='[ 学习]' where entry=32;
update mangos_string set content_default='[ 被动的]' where entry=33;
update mangos_string set content_default='[ 天赋]' where entry=34;
update mangos_string set content_default='[活跃的]' where entry=35;
update mangos_string set content_default='[ 完成]' where entry=36;
update mangos_string set content_default='(脱机)' where entry=37;
update mangos_string set content_default='开' where entry=38;
update mangos_string set content_default='关' where entry=39;
update mangos_string set content_default='你是: %s' where entry=40;
update mangos_string set content_default='看得见的' where entry=41;
update mangos_string set content_default='看不见的' where entry=42;
update mangos_string set content_default='完成了' where entry=43;
update mangos_string set content_default='你' where entry=44;
update mangos_string set content_default='<未知>' where entry=45;
update mangos_string set content_default='<错误>' where entry=46;
update mangos_string set content_default='<不存在的角色>' where entry=47;
update mangos_string set content_default='未知' where entry=48;
update mangos_string set content_default='你必须达到 %u 级后进入。' where entry=49;
update mangos_string set content_default='你必须达到 %u 级,并且拥有道具 %s 方可进入。' where entry=50;
update mangos_string set content_default='你好! 准备学习什么技能吗?' where entry=51;
update mangos_string set content_default='为项目的 Invaid 项目计数 (%u)%u' where entry=52;
update mangos_string set content_default='邮件不能有更多 %u 项目堆栈' where entry=53;
update mangos_string set content_default='新的口令不符合' where entry=54;
update mangos_string set content_default='你的口令不能是长于16字节，口令没有更改!' where entry=55;
update mangos_string set content_default='"那天的现在的信息:%s"' where entry=56;
update mangos_string set content_default='使用世界分贝: %s' where entry=57;
update mangos_string set content_default='使用手写体: %s' where entry=58;
update mangos_string set content_default='使用人事件AI: %s' where entry=59;
update mangos_string set content_default='在线玩家: %u (max: %u)' where entry=60;
update mangos_string set content_default='用户名称:' where entry=61;
update mangos_string set content_default='"世界通报:"' where entry=100;
update mangos_string set content_default='""" 地图: %u(%s) 地域: %u(%s) 地区: %u(%s)X: %f Y: %f Z: %f"""' where entry=101;
update mangos_string set content_default='%s 已远距离传送。' where entry=102;
update mangos_string set content_default='你可以召唤一个玩家到你的副本，前提是必须在与一队伍，而且你是队长。' where entry=103;
update mangos_string set content_default='你不能传送到玩家 %s 的副本，因为你们不在与一队伍。' where entry=104;
update mangos_string set content_default='传送到不是与一队伍的玩家 %s 的副本需要打开ＧＭ模式。' where entry=105;
update mangos_string set content_default='你不能传送到玩家 %s 从副本到副本。' where entry=106;
update mangos_string set content_default='你不能召唤这个玩家 %s 从副本到副本。' where entry=107;
update mangos_string set content_default='你正在召唤 %s% s。' where entry=108;
update mangos_string set content_default='系统帮助：你正在被 %s 召唤中。' where entry=109;
update mangos_string set content_default='你正在传送 %s% s 到 %s。' where entry=110;
update mangos_string set content_default='系统帮助：你正在被 %s 传送。' where entry=111;
update mangos_string set content_default='玩家 (%s) 不存在。' where entry=112;
update mangos_string set content_default='出现在 %s 的地点。' where entry=113;
update mangos_string set content_default='%s 出现在你的位置。' where entry=114;
update mangos_string set content_default='无效参数。' where entry=115;
update mangos_string set content_default='没有选定角色。' where entry=116;
update mangos_string set content_default='%s 不在与一小组里。' where entry=117;
update mangos_string set content_default='你改变了 %s 的血量值 HP 到 %i/%i。' where entry=118;
update mangos_string set content_default='%s 改变了你的血量值 HP 到 % i/%i。' where entry=119;
update mangos_string set content_default='你改变了 %s 的魔法值超自然力量到 % i/%i。' where entry=120;
update mangos_string set content_default='%s 改变了你的魔法值超自然力量到 % i/%i。' where entry=121;
update mangos_string set content_default='你改变了 %s 的能量值能源到 % i/%i。' where entry=122;
update mangos_string set content_default='%s 改变了你的能量值能源到 % i/%i。' where entry=123;
update mangos_string set content_default='当前的能量: %u' where entry=124;
update mangos_string set content_default='你改变了 %s 的怒气值愤怒到 %i/%i。' where entry=125;
update mangos_string set content_default='%s 改变了你的怒气值愤怒到 %i/%i。' where entry=126;
update mangos_string set content_default='你改变了 %s 的等级 LVL 到 % i。' where entry=127;
update mangos_string set content_default='GUID%i, 阵营是 %i, 旗子是 %i, npcflag 是 %i, DY 旗子是 %i' where entry=128;
update mangos_string set content_default='错误阵式: %u.(在 factiontemplate.dbc 中不发现)' where entry=129;
update mangos_string set content_default='你改变了 GUID=%i"s 阵营到 %i, 旗子到 %i,' where entry=130;
update mangos_string set content_default='你改变了 spellflatid=%i, val=%i, 标志 =%i' where entry=131;
update mangos_string set content_default='%s 改变了你的 spellflatid=%i, val=%i, 标志 =%i。' where entry=132;
update mangos_string set content_default='%s 获得了所有的计程节点 (直到注销).' where entry=133;
update mangos_string set content_default='%s 没有更多地可获得的计程节点 (仅显示容易接近的).' where entry=134;
update mangos_string set content_default='%s 给你进入所有计程车节点 (直到注销).' where entry=135;
update mangos_string set content_default='%s 已取消进出所有计程车节点 (仅显示仍然容易接近的).' where entry=136;
update mangos_string set content_default='你设置了所有的速度到 %2.2 f 从数值 %s。' where entry=137;
update mangos_string set content_default='%s 设置了你所有的速度到 %2.2 f 从数值。' where entry=138;
update mangos_string set content_default='你设置了移动速度到 %2.2 f 从数值 %s。' where entry=139;
update mangos_string set content_default='%s 设置了你的移动速度到 %2.2 f 从数值。' where entry=140;
update mangos_string set content_default='你设置了游泳速度到 %2.2 f 从数值 %s。' where entry=141;
update mangos_string set content_default='%s 设置了你的游泳速度到 %2.2 f 从数值。' where entry=142;
update mangos_string set content_default='设置了后退速度到 %2.2 f 从数值 %s。' where entry=143;
update mangos_string set content_default='%s 设置了你的后退速度到 %2.2 f 从数值。' where entry=144;
update mangos_string set content_default='你设置了飞行速度到 %2.2 f 从数值 %s。' where entry=145;
update mangos_string set content_default='%s 设置你的飞行速度到 %2.2 f 从数值。' where entry=146;
update mangos_string set content_default='你设置了这个比例 %2.2 f%s。' where entry=147;
update mangos_string set content_default='%s 设置你的比例为 %2.2 f。' where entry=148;
update mangos_string set content_default='没有此类骑术。' where entry=149;
update mangos_string set content_default='你把一个骑术送给 %s。' where entry=150;
update mangos_string set content_default='%s 送给你一个骑术。' where entry=151;
update mangos_string set content_default='"用户1: %i,增加: %i, 结果: %i"' where entry=152;
update mangos_string set content_default='你拿走了所有的铜币从 %s。' where entry=153;
update mangos_string set content_default='%s 拿走了你所有的铜币。' where entry=154;
update mangos_string set content_default='你拿走了 %i 铜币从 % s。' where entry=155;
update mangos_string set content_default='%s 拿走了 % i 铜币从你这里。' where entry=156;
update mangos_string set content_default='你把 %i 铜币给了 % s。' where entry=157;
update mangos_string set content_default='%s 给你 % i 铜币。' where entry=158;
update mangos_string set content_default='你听到声音 %u。' where entry=159;
update mangos_string set content_default='"用户2: %i,增加: %i, 结果: %i"' where entry=160;
update mangos_string set content_default='离开的一点点 %在领域中的 i%i。' where entry=161;
update mangos_string set content_default='固定的一点点 %在领域中的 i%i。' where entry=162;
update mangos_string set content_default='远距传送地点表是空的!' where entry=163;
update mangos_string set content_default='远距传送地点没被发现!' where entry=164;
update mangos_string set content_default='需要搜索参数。' where entry=165;
update mangos_string set content_default='没有远距传物地点符合您的请求。' where entry=166;
update mangos_string set content_default='发现地点是:' where entry=168;
update mangos_string set content_default='邮件寄给 %s' where entry=169;
update mangos_string set content_default='你试着听声音 %u 但是它并不存在。' where entry=170;
update mangos_string set content_default='你不能传送自己到自己!' where entry=171;
update mangos_string set content_default='伺候器主控台指令' where entry=172;
update mangos_string set content_default='你改变了古代北欧文字的力量 %s 到 %i/%i。' where entry=173;
update mangos_string set content_default='%s 改变了你的古代北欧文字力量到 %i/%i。' where entry=174;
update mangos_string set content_default='ID级别：％F，地面：％F，类型：％U，标志％U，状态：为％d。' where entry=175;
update mangos_string set content_default='没有选择。' where entry=200;
update mangos_string set content_default='对象 GUID 是: lowpart %u highpart %X' where entry=201;
update mangos_string set content_default='这个名字长度超过了 %i 字符。' where entry=202;
update mangos_string set content_default='错误，名字只能包含字符 A-Z 和 a-z。' where entry=203;
update mangos_string set content_default='次级名字太长超过了 %i 字符。' where entry=204;
update mangos_string set content_default='未能实施。' where entry=205;
update mangos_string set content_default='物品 "% i""% s" 以加入到清单且最大数 "% i" 复生时间 "% i"' where entry=206;
update mangos_string set content_default='物品 "% i" 在数据库里没有找到。' where entry=207;
update mangos_string set content_default='物品 "% i""% s" 已经从商人清单中删除。' where entry=208;
update mangos_string set content_default='物品 "% i" 没有找到在商人的清单里。' where entry=209;
update mangos_string set content_default='法术 %s 重置。' where entry=211;
update mangos_string set content_default='法术 %s 将在下次登陆时重置。' where entry=212;
update mangos_string set content_default='天赋 %s 重置。' where entry=213;
update mangos_string set content_default='天赋 %s 将在下次登陆时重置。' where entry=214;
update mangos_string set content_default='你的法术已经重置了。' where entry=215;
update mangos_string set content_default='你的天赋已经重置了。' where entry=216;
update mangos_string set content_default='未知的参数 "% s" 为。resetall 指令。 键入完整的正确参数名字。' where entry=217;
update mangos_string set content_default='法术将重置在所有玩家在重新登录后。 强烈推荐重新登录!' where entry=218;
update mangos_string set content_default='天赋将重置在所有玩家在重新登录后。 强烈推荐重新登录!' where entry=219;
update mangos_string set content_default='生物 (GUID: %u) 没有飞行点发现。' where entry=220;
update mangos_string set content_default='生物 (GUID: %u) 飞行终点没有找到。' where entry=221;
update mangos_string set content_default='生物 (GUID: %u) 没有飞行点发现 - 请用 "wpguid". 现在设法发现它由它的位置。。。' where entry=222;
update mangos_string set content_default='生物 (GUID: %u) 没有飞行点发现 - 这是一个问题.(独身者漂流物)' where entry=223;
update mangos_string set content_default='选择的生物被忽略 - 提供的 GUID 已经被占用。' where entry=224;
update mangos_string set content_default='生物 (GUID: %u) 没有找到。' where entry=225;
update mangos_string set content_default='您必须选择一个视觉飞行点。' where entry=226;
update mangos_string set content_default='没有找到视觉飞行点。' where entry=227;
update mangos_string set content_default='不能创建视觉飞行点的生物ID: %d' where entry=228;
update mangos_string set content_default='所有视觉飞行点消除。' where entry=229;
update mangos_string set content_default='不能创建飞行点- 生物的ID: %d' where entry=230;
update mangos_string set content_default='没有 GUID 被提供。' where entry=231;
update mangos_string set content_default='没有提供飞行点数值。' where entry=232;
update mangos_string set content_default='根据要求为 "% s".' where entry=233;
update mangos_string set content_default='飞行点 %i 添加到 GUID: %d' where entry=234;
update mangos_string set content_default='飞行点 %d 已添加。' where entry=235;
update mangos_string set content_default='飞行点已变动。' where entry=236;
update mangos_string set content_default='飞行点 %s 已修改。' where entry=237;
update mangos_string set content_default='飞行点出口成功。' where entry=238;
update mangos_string set content_default='没有飞行点被发现在数据库里。' where entry=239;
update mangos_string set content_default='文件已导入。' where entry=240;
update mangos_string set content_default='飞行点取消。' where entry=241;
update mangos_string set content_default='警告: 不能删除这个飞行点从世界里且ID: %d' where entry=242;
update mangos_string set content_default='出现这种情况，是因为飞行点过于远离你。' where entry=243;
update mangos_string set content_default='这个飞行点已经从数据库删除，但不是从世界这里。' where entry=244;
update mangos_string set content_default='他们将消失，当服务器重新引导之后。' where entry=245;
update mangos_string set content_default='飞行点 %d: 生物信息: %s, GUID: %d' where entry=246;
update mangos_string set content_default='等待时间: %d' where entry=247;
update mangos_string set content_default='模型 %d: %d' where entry=248;
update mangos_string set content_default='表情: %d' where entry=249;
update mangos_string set content_default='技能: %d' where entry=250;
update mangos_string set content_default='本文%d(ID: %i): %s' where entry=251;
update mangos_string set content_default='AI脚本: %s' where entry=252;
update mangos_string set content_default='强制修改玩家名 %s ，将于下次登录时生效。' where entry=253;
update mangos_string set content_default='强制修改玩家名 %s(GUID#%u) ，将于下次登录时生效。' where entry=254;
update mangos_string set content_default='飞行点-生物 (GUID: %u) 没有找到。' where entry=255;
update mangos_string set content_default='不能寻找 NPC。。。' where entry=256;
update mangos_string set content_default='生物运动方式设置为 "% s", 飞行点去除 (如果任何).' where entry=257;
update mangos_string set content_default='生物运动方式设置为 "% s", 飞行点没有去除。' where entry=258;
update mangos_string set content_default='错误值, 在或上的请用走开' where entry=259;
update mangos_string set content_default='设置已存储。' where entry=260;
update mangos_string set content_default='设置已存储，你可能需要重新清理你的客户缓存。' where entry=261;
update mangos_string set content_default='本地触发 (传送门) ID %u 没有发现!' where entry=262;
update mangos_string set content_default='目标地图或坐标无效 (X: %f Y: %f MapId: %u)' where entry=263;
update mangos_string set content_default='本地传送门无效 (X: %f Y: %f AreaId: %u)' where entry=264;
update mangos_string set content_default='地域 %u(%s) 是地图 %u(%s)的部份' where entry=265;
update mangos_string set content_default='没任何发现!' where entry=266;
update mangos_string set content_default='对像没有找到!' where entry=267;
update mangos_string set content_default='生物没有找到!' where entry=268;
update mangos_string set content_default='警告: 怪物发现超过一次 - 你将使用的是第一个在DB数据里的记录.' where entry=269;
update mangos_string set content_default='生物已经删除。' where entry=270;
update mangos_string set content_default='生物已经移动。' where entry=271;
update mangos_string set content_default='生物 (GUID:%u) 必须与玩家在与样的地图!' where entry=272;
update mangos_string set content_default='游戏对像 (GUID: %u) 没有找到。' where entry=273;
update mangos_string set content_default='游戏对像 (GUID: %u) 有一个参考于没有找到生物 %u 是名单，不能被删除。' where entry=274;
update mangos_string set content_default='游戏对像 (GUID: %u) 去除。' where entry=275;
update mangos_string set content_default='游戏对像 (GUID: %u) 转动。' where entry=276;
update mangos_string set content_default='游戏对像 (GUID: %u) 移动。' where entry=277;
update mangos_string set content_default='你必须选择一个商人' where entry=278;
update mangos_string set content_default='你必须使用物品的遗传素质' where entry=279;
update mangos_string set content_default='商人设置了太多的物品 (最多 128)' where entry=280;
update mangos_string set content_default='你不能踢出你自己，使用结束代替。' where entry=281;
update mangos_string set content_default='角色 %s 已踢出。' where entry=282;
update mangos_string set content_default='接受悄悄话: %s' where entry=284;
update mangos_string set content_default='接受悄悄话: 在' where entry=285;
update mangos_string set content_default='接受悄悄话: 走开' where entry=286;
update mangos_string set content_default='生物 (GUID: %u) 没有找到。' where entry=287;
update mangos_string set content_default='票数量: %i 出示新的票: %s' where entry=288;
update mangos_string set content_default='新票开始于 %s' where entry=289;
update mangos_string set content_default='"票 %s(最后的更新: %s):%s"' where entry=290;
update mangos_string set content_default='新票显示: 在' where entry=291;
update mangos_string set content_default='新票显示: 走开' where entry=292;
update mangos_string set content_default='票 %i 不存在。' where entry=293;
update mangos_string set content_default='所有票已删除。' where entry=294;
update mangos_string set content_default='角色 %s 票已删除。' where entry=295;
update mangos_string set content_default='票已删除。' where entry=296;
update mangos_string set content_default='复生间隔改变为: %i' where entry=297;
update mangos_string set content_default='复生时间改变为: %i' where entry=298;
update mangos_string set content_default='%s 的荣誉被设置到 % u!' where entry=299;
update mangos_string set content_default='你被关闭了 %s 的聊天时间 % u 分钟。' where entry=301;
update mangos_string set content_default='玩的聊天已经可以使用。' where entry=302;
update mangos_string set content_default='你的聊天已经可以使用。' where entry=303;
update mangos_string set content_default='你已经可以使用 %s 的聊天了。' where entry=304;
update mangos_string set content_default='阵营 %s(%u) 名誉 %s 被设置成 %5 d!' where entry=305;
update mangos_string set content_default='竞技场点 %s 被设置成 %u!' where entry=306;
update mangos_string set content_default='没有阵营被发现' where entry=307;
update mangos_string set content_default='阵营 %i 未知!' where entry=308;
update mangos_string set content_default='无效的参数 %s' where entry=309;
update mangos_string set content_default='三角州必须是在 0之间和 %d(包含)在内的' where entry=310;
update mangos_string set content_default='%d - |cffffffff|Hfaction:%d|h[%s]|h|r' where entry=311;
update mangos_string set content_default='[看得见的]' where entry=312;
update mangos_string set content_default='[在战争]' where entry=313;
update mangos_string set content_default='[和平被迫的]' where entry=314;
update mangos_string set content_default='[隐藏的]' where entry=315;
update mangos_string set content_default='[看不见的被迫]' where entry=316;
update mangos_string set content_default='[不活动的]' where entry=317;
update mangos_string set content_default='仇恨' where entry=318;
update mangos_string set content_default='敌对' where entry=319;
update mangos_string set content_default='不友好' where entry=320;
update mangos_string set content_default='中立' where entry=321;
update mangos_string set content_default='友好的' where entry=322;
update mangos_string set content_default='荣誉的' where entry=323;
update mangos_string set content_default='尊敬的' where entry=324;
update mangos_string set content_default='高贵的' where entry=325;
update mangos_string set content_default='阵营 %s(%u) 不能有荣誉。' where entry=326;
update mangos_string set content_default='[没有名誉]' where entry=327;
update mangos_string set content_default='在帐户的角色 %s(ID: %u)' where entry=328;
update mangos_string set content_default='  %s (GUID %u)' where entry=329;
update mangos_string set content_default='没有玩家发现!' where entry=330;
update mangos_string set content_default='广大的项目费用 %u 不存在' where entry=331;
update mangos_string set content_default='打开GM状态' where entry=332;
update mangos_string set content_default='关闭GM状态' where entry=333;
update mangos_string set content_default='GM 闲谈半自动防空警戒管制组织是在' where entry=334;
update mangos_string set content_default='GM 闲谈半自动防空警戒管制组织是走开' where entry=335;
update mangos_string set content_default='你修理所有的 %s 项目。' where entry=336;
update mangos_string set content_default='你所有的项目修复的被 %s。' where entry=337;
update mangos_string set content_default='你组 waterwalk 模态 %s 为 %s。' where entry=338;
update mangos_string set content_default='你的 waterwalk 模态 %s 被 %s。' where entry=339;
update mangos_string set content_default='%s 现在是下列各项你。' where entry=340;
update mangos_string set content_default='%s 是不下列各项你。' where entry=341;
update mangos_string set content_default='%s 是现在不下列各项你。' where entry=342;
update mangos_string set content_default='人 (进入: %u) 不能够是驯养。' where entry=343;
update mangos_string set content_default='你已经有伴侣动物。' where entry=344;
update mangos_string set content_default='被迫的为玩家自定 %s 将会是在下一个登录请求了。' where entry=345;
update mangos_string set content_default='被迫的为玩家自定 %s(GUID#%u) 意志是在下一个登录请求了。' where entry=346;
update mangos_string set content_default='TaxiNode ID %u 不发现!' where entry=347;
update mangos_string set content_default='游戏物体 (进入: %u) 有病人数据而且不能是产' where entry=348;
update mangos_string set content_default='|cffff 0000[ 系统信息]:|rScripts 再装货' where entry=400;
update mangos_string set content_default='你改变了 %s 的安全等级为 % i。' where entry=401;
update mangos_string set content_default='%s 改变了你的安全等级为 % i。' where entry=402;
update mangos_string set content_default='你这是低的防护等级。' where entry=403;
update mangos_string set content_default='生物移动点取消。' where entry=404;
update mangos_string set content_default='生物移动点生效。' where entry=405;
update mangos_string set content_default='这个本地的天气不能被更改。' where entry=406;
update mangos_string set content_default='本服务器天气系统取消。' where entry=407;
update mangos_string set content_default='%s 被禁止的为 % s。 作业: %s。' where entry=408;
update mangos_string set content_default='%s 被永久禁止的为 % s。' where entry=409;
update mangos_string set content_default='%s% s 不发现' where entry=410;
update mangos_string set content_default='%s 已解除禁止。' where entry=411;
update mangos_string set content_default='出现错误取消禁令 %s。' where entry=412;
update mangos_string set content_default='没有这个帐户。' where entry=413;
update mangos_string set content_default='没有这个角色。' where entry=414;
update mangos_string set content_default='没有这样的 IP 在禁止名单。' where entry=415;
update mangos_string set content_default='账号 %s 从来没被禁止。' where entry=416;
update mangos_string set content_default='历史禁止帐户 %s:' where entry=417;
update mangos_string set content_default='禁止日期: %s 禁止时间: %s 引导间隔: %s 原因: %s 作业者: %s' where entry=418;
update mangos_string set content_default='信息。' where entry=419;
update mangos_string set content_default='从不' where entry=420;
update mangos_string set content_default='是的' where entry=421;
update mangos_string set content_default='没有' where entry=422;
update mangos_string set content_default='IP 地址: %s 禁止日期: %s 解除禁止日期: %s 剩下: %s R' where entry=423;
update mangos_string set content_default='没有符合的 IP 禁止地址。' where entry=424;
update mangos_string set content_default='没有符合的帐户。' where entry=425;
update mangos_string set content_default='没有禁用的账号相符合。' where entry=426;
update mangos_string set content_default='下面的 IP 地址符合您的格局:' where entry=427;
update mangos_string set content_default='以下帐户符合您的查询:' where entry=428;
update mangos_string set content_default='你学会了许多法术或技能。' where entry=429;
update mangos_string set content_default='你已经学会了所有的会职业法术。' where entry=430;
update mangos_string set content_default='你已经学会了所有的本职业天赋。' where entry=431;
update mangos_string set content_default='你已经学会了所有的语言。' where entry=432;
update mangos_string set content_default='你学会了所有手工艺技能和食谱。' where entry=433;
update mangos_string set content_default='不能寻找 "% s"' where entry=434;
update mangos_string set content_default='无效的物品遗传素质: %u' where entry=435;
update mangos_string set content_default='没有找到物品!' where entry=436;
update mangos_string set content_default='无效的游戏物品对像遗传素质: %u' where entry=437;
update mangos_string set content_default='找到物品 %u: %u( 库存 %u 邮件 % u 拍卖 %u)' where entry=438;
update mangos_string set content_default='找到物品对像 %u: %u' where entry=439;
update mangos_string set content_default='无效的生物遗传素质: %u' where entry=440;
update mangos_string set content_default='找到生物 %u: %u' where entry=441;
update mangos_string set content_default='没有地区被发现!' where entry=442;
update mangos_string set content_default='没有找到物品集!' where entry=443;
update mangos_string set content_default='没有找到此技能!' where entry=444;
update mangos_string set content_default='没有找到此法术!' where entry=445;
update mangos_string set content_default='没有找到此任务!' where entry=446;
update mangos_string set content_default='没有找到此生物!' where entry=447;
update mangos_string set content_default='没有找到此游戏物品对像!' where entry=448;
update mangos_string set content_default='墓地 #%u 不存在。' where entry=449;
update mangos_string set content_default='墓地 #%u 已经连接到本地 #% u(当前).' where entry=450;
update mangos_string set content_default='墓地 #%u 连接到本地 #% u(当前).' where entry=451;
update mangos_string set content_default='墓地 #%u 不能连接到子本地或不存在的本地 #% u(内部错误).' where entry=452;
update mangos_string set content_default='没有阵营在墓地且遗传素质=#%u, 请修复你的分贝数据库' where entry=454;
update mangos_string set content_default='错误的队伍, 请修复你的数据库' where entry=455;
update mangos_string set content_default='任何' where entry=456;
update mangos_string set content_default='联盟' where entry=457;
update mangos_string set content_default='部落' where entry=458;
update mangos_string set content_default='墓地ID #%u(阵营: %s) 是最近的距此本地 zoneID#%u。' where entry=459;
update mangos_string set content_default='本地地域 #%u 没有一个连接的墓地。' where entry=460;
update mangos_string set content_default='本地地域 #%u 没有一个连接的墓地为阵营阵营: %s。' where entry=461;
update mangos_string set content_default='远距传物地点已经存在!' where entry=462;
update mangos_string set content_default='远距传送地点增加。' where entry=463;
update mangos_string set content_default='远距传送地点没增加: 数据库错误。' where entry=464;
update mangos_string set content_default='远距传送地点被删除。' where entry=465;
update mangos_string set content_default='没有 taxinodes 发现!' where entry=466;
update mangos_string set content_default='目标单位 (单位) 有 %d 光环气味:' where entry=467;
update mangos_string set content_default='遗传素质: %d eff: %d 类型: %d 期间: %d maxduration: %d 名字: %s% s%s 投手: %s% u' where entry=468;
update mangos_string set content_default='目标单位有 %类型的 d 气味 %d:' where entry=469;
update mangos_string set content_default='id: %d eff: %d amount: %d' where entry=470;
update mangos_string set content_default='任务 %u 没有找到。' where entry=471;
update mangos_string set content_default='任务 %u 由物品触发。 为正确工作，请, 添加物品到库里并且开始这个任务的正常方式: 。additem%u' where entry=472;
update mangos_string set content_default='任务清除。' where entry=473;
update mangos_string set content_default='[ 奖赏]' where entry=474;
update mangos_string set content_default='[ 完成]' where entry=475;
update mangos_string set content_default='[活跃的]' where entry=476;
update mangos_string set content_default='%s 的飞行模式为 % s' where entry=477;
update mangos_string set content_default='作业代码作业码 %u 发送到 (送了到)%s' where entry=478;
update mangos_string set content_default='角色加载成功!' where entry=479;
update mangos_string set content_default='加载角色失败!' where entry=480;
update mangos_string set content_default='卸载角色成功!' where entry=481;
update mangos_string set content_default='卸载角色失败!' where entry=482;
update mangos_string set content_default='魔法 %u 破裂，并且不允许使用或学习!' where entry=483;
update mangos_string set content_default='技能值 %u(%s) 为角色 %s 设置到 % u 并且当前最大设置到 %u.(没有固定 (天赋) 奖励)' where entry=484;
update mangos_string set content_default='角色 %s 必须拥有技能 % u(%s) 在使用这个指令之前。' where entry=485;
update mangos_string set content_default='错误的技能遗传素质 (%u)' where entry=486;
update mangos_string set content_default='你学会了ＧＭ默认的法术和技能。' where entry=487;
update mangos_string set content_default='你已经学了这个法术。' where entry=488;
update mangos_string set content_default='目标目标 (%s) 已经学习了那些法术。' where entry=489;
update mangos_string set content_default='%s 不懂那些法术。' where entry=490;
update mangos_string set content_default='您已经忘记了那个法术。' where entry=491;
update mangos_string set content_default='所有的法术冷却清除为 %s。' where entry=492;
update mangos_string set content_default='法术 %u 冷却清除为 %s。' where entry=493;
update mangos_string set content_default='指令: Additem, itemId=%i, 数量 =%i' where entry=494;
update mangos_string set content_default='指令: Additemset, itemsetId=%i' where entry=495;
update mangos_string set content_default='删除物品ID =%i, 数量 =%i 从 %s' where entry=496;
update mangos_string set content_default='不能创建物品 "% i"(数量数量: %i)' where entry=497;
update mangos_string set content_default='系统帮助：你需要提供一个公会名字!' where entry=498;
update mangos_string set content_default='系统帮助：玩家没有被找到!' where entry=499;
update mangos_string set content_default='系统帮助：玩家已经有一个公会!' where entry=500;
update mangos_string set content_default='公会没被创建! (是否已经存在?)' where entry=501;
update mangos_string set content_default='没有物品从物品库 "% u" 里找到。' where entry=502;
update mangos_string set content_default='距离: (3D) %f (2D) %f (Exact 3D) %f (Exact 2D) %f yards.' where entry=503;
update mangos_string set content_default='物品 "% i""% s" 背包 %i' where entry=504;
update mangos_string set content_default='物品 "% i" 不存在。' where entry=505;
update mangos_string set content_default='物品 "% i""% s" 已加入背包 %i' where entry=506;
update mangos_string set content_default='物品存储失败!' where entry=507;
update mangos_string set content_default='%d- 拥有者: %s(guid: %u 帐户: %u)%s' where entry=508;
update mangos_string set content_default='%d- 寄件人: %s(guid: %u 帐户: %u) 接收器: %s(guid: %u 帐户: %u)%s' where entry=509;
update mangos_string set content_default='%d- 拥有者: %s(guid: %u 帐户: %u)%s' where entry=510;
update mangos_string set content_default='错误的联编类型!' where entry=511;
update mangos_string set content_default='%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0:0|h[%s]|h|r ' where entry=512;
update mangos_string set content_default='%d - |cffffffff|Hquest:%d:%d|h[%s]|h|r %s' where entry=513;
update mangos_string set content_default='%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ' where entry=514;
update mangos_string set content_default='%d%s - |cffffffff|H生物:%d|h[%s X:%f Y:%f Z:%f 地图号:%d]|h|r' where entry=515;
update mangos_string set content_default='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' where entry=516;
update mangos_string set content_default='%d (Entry: %d) - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' where entry=517;
update mangos_string set content_default='%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ' where entry=518;
update mangos_string set content_default='|cffffffff|Htele:%s|h[%s]|h|r ' where entry=519;
update mangos_string set content_default='%d - |cffffffff|Hspell:%d|h[%s]|h|r ' where entry=520;
update mangos_string set content_default='%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s' where entry=521;
update mangos_string set content_default='游戏物体 (进入: %u) 不发现' where entry=522;
update mangos_string set content_default='>> 游戏物体 %s(GUID: %u) 在 %f% f%f。 定方位 %f。' where entry=523;
update mangos_string set content_default='"挑选的物体:|cffffffff| Hgameobject:%d| h[%s]| h|r GUID: %u ID: %u  X: %f Y: %f Z: %f MapId: %u  定方位: %f"' where entry=524;
update mangos_string set content_default='>> Add Game Object ''%i'' (%s) (GUID: %i) added at ''%f %f %f''.' where entry=525;
update mangos_string set content_default='%s(lowguid: %u) 运动产生器堆栈:' where entry=526;
update mangos_string set content_default='懒惰的' where entry=527;
update mangos_string set content_default='随意' where entry=528;
update mangos_string set content_default='航点' where entry=529;
update mangos_string set content_default='动物随意' where entry=530;
update mangos_string set content_default='困惑的' where entry=531;
update mangos_string set content_default='对玩家对准了 %s(lowguid%u)' where entry=532;
update mangos_string set content_default='对人对准了 %s(lowguid%u)' where entry=533;
update mangos_string set content_default='对准到 <无效力的>' where entry=534;
update mangos_string set content_default='家运动到 (X:%f Y:%f Z:%f)' where entry=535;
update mangos_string set content_default='家运动对于玩家是二手的?!?' where entry=536;
update mangos_string set content_default='出租汽车飞行' where entry=537;
update mangos_string set content_default='未知者运动产生器 (%u)' where entry=538;
update mangos_string set content_default='玩家选择NPC DB GUID：％U，当前GUID：％U。声望：％u.npc标志：％U。输入：％U。显示ID：％U（原住民：％U）。' where entry=539;
update mangos_string set content_default='水平: %u。' where entry=540;
update mangos_string set content_default='健康 (基础): %u。 (最大): %u。 (涌流): %u。' where entry=541;
update mangos_string set content_default='单位旗子: %u。电动旗子: %u。阵营型板: %u。' where entry=542;
update mangos_string set content_default='战利品: %u 扒手: %u 剥皮: %u' where entry=543;
update mangos_string set content_default='位置: %f% f%f。' where entry=544;
update mangos_string set content_default='*** 是一个销售师!' where entry=545;
update mangos_string set content_default='*** 是一个训练师!' where entry=546;
update mangos_string set content_default='副本ID: %u' where entry=547;
update mangos_string set content_default='a”? 第一阶段: %u' where entry=846;
update mangos_string set content_default='a”? 种族: %s %s, %s' where entry=844;
update mangos_string set content_default='a”? 活着 ?: %s' where entry=845;
update mangos_string set content_default='%s 探索了所有地区。' where entry=551;
update mangos_string set content_default='%s 没有更多的探索区。' where entry=552;
update mangos_string set content_default='%s 你探索了所有地带。' where entry=553;
update mangos_string set content_default='%s 你掩藏了所有本地。' where entry=554;
update mangos_string set content_default='悬停启用' where entry=555;
update mangos_string set content_default='系统帮助：你的等级提升 (%i)' where entry=557;
update mangos_string set content_default='系统帮助：你的等级下降 (%i)' where entry=558;
update mangos_string set content_default='你的等级进度已复位。' where entry=559;
update mangos_string set content_default='该地区已被定为探索。' where entry=560;
update mangos_string set content_default='本地被设置了依照没被探索。' where entry=561;
update mangos_string set content_default='GUID=％日期索引：％i的值：％i个。' where entry=562;
update mangos_string set content_default='您可以更改 GUID=%i ''s 更新索引: %i value to %i.' where entry=563;
update mangos_string set content_default='价值索引 %u 太是大的到 %u(计数: %u)。' where entry=564;
update mangos_string set content_default='固定的 %u uint 32 价值:[作业码]:%u[ 价值]:%u' where entry=565;
update mangos_string set content_default='你组 %u 领域:%对 uint 32 价值的 u: %u' where entry=566;
update mangos_string set content_default='固定的 %u 漂流物价值:[作业码]:%u[ 价值]:%f' where entry=567;
update mangos_string set content_default='你组 %u 领域:%i 对漂流物价值: %f' where entry=568;
update mangos_string set content_default='拿 %u uint 32 价值:[作业码]:%u[ 价值]:%u' where entry=569;
update mangos_string set content_default='uint 32 价值 %u 在 %u 是: %u' where entry=570;
update mangos_string set content_default='拿 %u 漂流物价值:[作业码]:%u[ 价值]:%f' where entry=571;
update mangos_string set content_default='漂流物 %u 价值在 %u 是: %f' where entry=572;
update mangos_string set content_default='.Set32Bit:[OPCODE]:%u [VALUE]:%u' where entry=573;
update mangos_string set content_default='您可以设置位元字段:%u to 值: %u' where entry=574;
update mangos_string set content_default='。Mod32 价值:[作业码]:%u[ 价值]:%i' where entry=575;
update mangos_string set content_default='你修正了领域的价值:%u 对价值: %u' where entry=576;
update mangos_string set content_default='你现在处于隐身状态。' where entry=577;
update mangos_string set content_default='你现在处于可见状态。' where entry=578;
update mangos_string set content_default='挑选的玩家或人不有受害人。' where entry=579;
update mangos_string set content_default='玩家 %s 学会了所有的本种族本职业的魔法，包括任何奖励的技能。' where entry=580;
update mangos_string set content_default='发现近的 gameobjects:(距离 %f) %u' where entry=581;
update mangos_string set content_default='清除时间: 全部:%s 保持:%s' where entry=582;
update mangos_string set content_default='%d - |cffffffff|H游戏事件:%d|h[%s]|h|r%s' where entry=583;
update mangos_string set content_default='没有事件被找到!' where entry=584;
update mangos_string set content_default='事件不存在!' where entry=585;
update mangos_string set content_default='" 事件 %u: %s% s 开始: %s 结束: %s 发生: %s 全程: %s 下一次状态改变: %s"' where entry=586;
update mangos_string set content_default='事件 %u 已经开始!' where entry=587;
update mangos_string set content_default='事件 %u 没有开始!' where entry=588;
update mangos_string set content_default='点运动到 (X:%f Y:%f Z:%f)' where entry=589;
update mangos_string set content_default='恐惧运动' where entry=590;
update mangos_string set content_default='转移运动' where entry=591;
update mangos_string set content_default='你有有学问的整符咒在手艺: %s' where entry=592;
update mangos_string set content_default='现在禁止了帐户:' where entry=593;
update mangos_string set content_default='|    帐户    | 禁止格式    | 解除禁止时间| 是禁止被    | 禁止理由 |' where entry=594;
update mangos_string set content_default='现在禁止了 IPs:' where entry=595;
update mangos_string set content_default='|      IP       | 禁止格式    | 解除禁止时间| 是禁止被    | 禁止理由 |' where entry=596;
update mangos_string set content_default='在线GM:' where entry=597;
update mangos_string set content_default='|    帐户    | GM|' where entry=598;
update mangos_string set content_default='没有游戏管理员。' where entry=599;
update mangos_string set content_default='联盟获得胜利!' where entry=600;
update mangos_string set content_default='部落获得胜利!' where entry=601;
update mangos_string set content_default='战场战歌峡谷争夺分钟倒计时中。。。' where entry=602;
update mangos_string set content_default='战场战歌峡谷争夺，在 30 秒后开始。大家做好准备!' where entry=603;
update mangos_string set content_default='战场战歌峡谷争夺正式开始!' where entry=604;
update mangos_string set content_default='$n 夺取了部落旗子!' where entry=605;
update mangos_string set content_default='$n 夺取了联盟旗子!' where entry=606;
update mangos_string set content_default='部落旗子被 $n 降下!' where entry=607;
update mangos_string set content_default='联盟旗子被 $n 降下!' where entry=608;
update mangos_string set content_default='联盟旗子被 $n 返回了到它的基地!' where entry=609;
update mangos_string set content_default='部落旗子被 $n 返回了到它的基地!' where entry=610;
update mangos_string set content_default='部落旗子被 $n 拾起!' where entry=611;
update mangos_string set content_default='魔兽世界：联盟旗子被 $n 拾起!' where entry=612;
update mangos_string set content_default='旗子现在被安置在他们的基地。' where entry=613;
update mangos_string set content_default='联盟旗帜已经被重置' where entry=614;
update mangos_string set content_default='联盟旗帜已经被重置!' where entry=615;
update mangos_string set content_default='战场暴风之眼争夺分钟倒计时中....' where entry=636;
update mangos_string set content_default='战场暴风之眼争夺，在 30 秒后开始。大家做好准备!。' where entry=637;
update mangos_string set content_default='战场暴风之眼争夺正式开始!!' where entry=638;
update mangos_string set content_default='联盟' where entry=650;
update mangos_string set content_default='部落' where entry=651;
update mangos_string set content_default='兽栏' where entry=652;
update mangos_string set content_default='铁匠铺' where entry=653;
update mangos_string set content_default='农场' where entry=654;
update mangos_string set content_default='伐木场' where entry=655;
update mangos_string set content_default='金矿' where entry=656;
update mangos_string set content_default='此 %s 采取了 % s' where entry=657;
update mangos_string set content_default='$n 保卫了 % s' where entry=658;
update mangos_string set content_default='$n 攻击了 % s' where entry=659;
update mangos_string set content_default='$n 主持这个 % s 吧! 如果听之任之, 这个 %s 将在分钟之内控制它!' where entry=660;
update mangos_string set content_default='战场阿拉西盆地争夺分钟倒计时中。。。' where entry=661;
update mangos_string set content_default='战场阿拉西盆地争夺，在 30 秒后开始。大家做好准备!' where entry=662;
update mangos_string set content_default='战场阿拉西盆地争夺正式开始!' where entry=663;
update mangos_string set content_default='联盟已收集到 $1776 W 资源, 并已接近胜利!' where entry=664;
update mangos_string set content_default='部落已收集到 $1777 W 资源, 并已接近胜利!' where entry=665;
update mangos_string set content_default='你在最近的 %s 战斗之后，我们努力想为你颁发一个荣誉标志却没有成功，结束后你会发现这个荣誉标志的，但不是此刻,感谢你在 %s 的战斗。' where entry=666;
update mangos_string set content_default='联盟控制魔术师塔!' where entry=667;
update mangos_string set content_default='部落控制魔术师塔!' where entry=668;
update mangos_string set content_default='联盟控制 Draenei 毁灭!' where entry=669;
update mangos_string set content_default='部落控制 Draenei 毁灭!' where entry=670;
update mangos_string set content_default='联盟控制血向导塔!' where entry=671;
update mangos_string set content_default='部落控制血向导塔!' where entry=672;
update mangos_string set content_default='联盟有控制 Fel 再断言毁灭!' where entry=673;
update mangos_string set content_default='部落有控制 Fel 再断言毁灭!' where entry=674;
update mangos_string set content_default='联盟失去魔术师塔的控制!' where entry=675;
update mangos_string set content_default='部落失去魔术师塔的控制!' where entry=676;
update mangos_string set content_default='联盟有 Draenei 毁灭的失去的控制!' where entry=677;
update mangos_string set content_default='部落有 Draenei 毁灭的失去的控制!' where entry=678;
update mangos_string set content_default='联盟失去血向导塔的控制!' where entry=679;
update mangos_string set content_default='部落失去血向导塔的控制!' where entry=680;
update mangos_string set content_default='联盟有 Fel 的失去的控制再断言毁灭!' where entry=681;
update mangos_string set content_default='部落有 Fel 的失去的控制再断言毁灭!' where entry=682;
update mangos_string set content_default='%s 有带旗子!' where entry=683;
update mangos_string set content_default='联盟取得了旗子!' where entry=684;
update mangos_string set content_default='部落取得了旗子!' where entry=685;
update mangos_string set content_default='旗子已经被降下!' where entry=686;
update mangos_string set content_default='旗帜已经被重置' where entry=687;
update mangos_string set content_default='你必须达到等级 %u 才能进入竞技场。' where entry=700;
update mangos_string set content_default='一分钟后竞技场争斗开始!' where entry=701;
update mangos_string set content_default='三十秒后竞技场争斗开始!' where entry=702;
update mangos_string set content_default='十五秒后竞技场争斗开始!' where entry=703;
update mangos_string set content_default='竞技场争斗开始了!' where entry=704;
update mangos_string set content_default='你必须等待 %s 才能继续喊话。' where entry=705;
update mangos_string set content_default='这些道具在装备/ 存放中出现一个问题。' where entry=706;
update mangos_string set content_default='%s 免打扰状态下不能收到悄悄话: %s' where entry=707;
update mangos_string set content_default='%s 不在机器旁: %s' where entry=708;
update mangos_string set content_default='请勿打扰' where entry=709;
update mangos_string set content_default='不在机器旁' where entry=710;
update mangos_string set content_default='等待的队伍状态为 %s(Lvl: %u 到 %u) 排队了联盟: %u(需要至少 %u 更多) 排队了部落: %u(需要至少 %u 更多)' where entry=711;
update mangos_string set content_default='|cffff 0000[ BG 等待的队伍广播员]:|r% s-- [%u-%u] 一: %u/%u, H: %u/%u| r' where entry=712;
update mangos_string set content_default='你必须是水平 %u 对接合处竞技场队!' where entry=713;
update mangos_string set content_default='你做不会战场水平需求' where entry=715;
update mangos_string set content_default='|cffff 0000[ BG 等待的队伍广播员]:|r% s-- [%u-%u] 开始!|r' where entry=717;
update mangos_string set content_default='|cffff 0000[ 竞技场等待的队伍广播员]:|r 所有的竞技场 -- 三加 : %ux% u: %u| r' where entry=718;
update mangos_string set content_default='|cffff0000[竞技场队列信息通知]:|r %s -- 已结束 : %ux%u : %u|r' where entry=719;
update mangos_string set content_default='你的团体对这一个战场是太大的。 请对接合处重新编组。' where entry=720;
update mangos_string set content_default='你的团体对这一个竞技场是太大的。 请对接合处重新编组。' where entry=721;
update mangos_string set content_default='你的团体在你的竞技场队中不有成员。 请对接合处重新编组。' where entry=722;
update mangos_string set content_default='你的团体对接合处这个比赛没有充足玩家。' where entry=723;
update mangos_string set content_default='黄金队赢!' where entry=724;
update mangos_string set content_default='格林队赢!' where entry=725;
update mangos_string set content_default='没有足够的玩家。如果没有更多玩家加入以平衡人数，战场将在数分钟内结束。' where entry=726;
update mangos_string set content_default='你的团体有一个脱机成员。 以前请距离他参加。' where entry=727;
update mangos_string set content_default='你的团体有来自反对阵营的玩家。 你不能如一个团体的接合处战场。' where entry=728;
update mangos_string set content_default='你的团体有来自不与的战场 brakets 的玩家。 你不能如团体的接合处。' where entry=729;
update mangos_string set content_default='某人在你的宴会中已经在这一个战场等待的队伍中。 (S)他必须休假它在参加如团体之前。' where entry=730;
update mangos_string set content_default='某人在你的宴会中是背弃者。 你不能如团体的接合处。' where entry=731;
update mangos_string set content_default='某人在你的宴会中已经在三个战场等待的队伍中。 你不能够如团体的接合处。' where entry=732;
update mangos_string set content_default='你对一个战场或竞技场地图不能够利用心灵传动。' where entry=733;
update mangos_string set content_default='你对一个战场或竞技场地图不能够召唤玩家。' where entry=734;
update mangos_string set content_default='你在 GM 模态的必须是对在一个战场中的一个玩家利用心灵传动。' where entry=735;
update mangos_string set content_default='你对来自另外的一个战场的一个战场不能够利用心灵传动。 首先请休假现在的战场。' where entry=736;
update mangos_string set content_default='竞技场为调试被设置成 1v 1 。 因此, 与样地做不接合处团体。' where entry=737;
update mangos_string set content_default='竞技场被设置成常态 playercount 。' where entry=738;
update mangos_string set content_default='战场为调试被设置成 1v 0 。' where entry=739;
update mangos_string set content_default='战场被设置成常态 playercount 。' where entry=740;
update mangos_string set content_default='根据队伍等级计算竞技场点数中，也许将花上数分钟的时间。请等待……' where entry=741;
update mangos_string set content_default='正在为玩家发放竞技场点数……' where entry=742;
update mangos_string set content_default='玩家竞技场点数设置完毕。' where entry=743;
update mangos_string set content_default='对已加入竞技场队伍修改竞技场点数等，对在线玩家发送更新的状态...' where entry=744;
update mangos_string set content_default='修改完成。' where entry=745;
update mangos_string set content_default='完成清除竞技场点数。' where entry=746;
update mangos_string set content_default='不是充足玩家。 这一场游戏意志结束在 %u 最小。' where entry=750;
update mangos_string set content_default='不是充足玩家。 这一场游戏意志结束在 %u 秒。' where entry=751;
update mangos_string set content_default='只有部落能使用哪一入口' where entry=753;
update mangos_string set content_default='阿拉希盆地的战斗将在2分钟后开始。' where entry=754;
update mangos_string set content_default='风暴之眼的战斗将在2分钟后开始。' where entry=755;
update mangos_string set content_default='涌流挑选的名称对于玩家 %s 重新设置如不是已知现在。' where entry=356;
update mangos_string set content_default='名称 %u(%s) 组如涌流挑选的名称对于玩家 %s。' where entry=355;
update mangos_string set content_default='名称 %u(%s) 离开的从已知的名称目录对于玩家 %s。' where entry=354;
update mangos_string set content_default='%d (idx:%d) - [%s %s] %s %s ' where entry=350;
update mangos_string set content_default='没有名称发现!' where entry=351;
update mangos_string set content_default='病人名称遗传素质: %u' where entry=352;
update mangos_string set content_default='名称 %u(%s) 附加的对已知的名称目录对于玩家 %s。' where entry=353;
update mangos_string set content_default='%d (idx:%d) - |cffffffff|Htitle:%d|h[%s %s]|h|r %s %s ' where entry=349;
update mangos_string set content_default='直到给 Alterac 山谷的战争 30 秒开始。 准备你们自己!' where entry=785;
update mangos_string set content_default='给 Alterac 山谷的战争有开始!' where entry=786;
update mangos_string set content_default='联盟队是流动的由于增强!' where entry=787;
update mangos_string set content_default='无效的名称' where entry=800;
update mangos_string set content_default='你做不已经充足黄金' where entry=801;
update mangos_string set content_default='你做不已经充足自由的位置' where entry=802;
update mangos_string set content_default='你的合伙人做不已经充足自由的袋子位置' where entry=803;
update mangos_string set content_default='你做不已经许可运行功能' where entry=804;
update mangos_string set content_default='未知者语言' where entry=805;
update mangos_string set content_default='你不知道那一种语言' where entry=806;
update mangos_string set content_default='请提供角色名字' where entry=807;
update mangos_string set content_default='玩家 %s 不发现或脱机' where entry=808;
update mangos_string set content_default='解释角色 %s 不发现' where entry=809;
update mangos_string set content_default='|Hplayer:$N|h[$N]|h达成成就$a!' where entry=810;
update mangos_string set content_default='公会会长' where entry=811;
update mangos_string set content_default='官员' where entry=812;
update mangos_string set content_default='退伍军人' where entry=813;
update mangos_string set content_default='成员' where entry=814;
update mangos_string set content_default='入会' where entry=815;
update mangos_string set content_default='警告：你进入了不允许飞行的地区，即将解除飞行坐骑！' where entry=816;
update mangos_string set content_default='离开 daemon 。。。' where entry=1000;
update mangos_string set content_default='帐户划除: %s' where entry=1001;
update mangos_string set content_default='帐户 %s 不划除了 (或许 sql 文件格式是更新)' where entry=1002;
update mangos_string set content_default='帐户 %s 不划除了 (未知者错误)' where entry=1003;
update mangos_string set content_default='帐户产生: %s' where entry=1004;
update mangos_string set content_default='帐户名字不可能是比 16个角色 (客户界限) 长, 帐户不产生了!' where entry=1005;
update mangos_string set content_default='和这个名字的帐户已经存在!' where entry=1006;
update mangos_string set content_default='帐户 %s 不产生了 (或许 sql 文件格式是更新)' where entry=1007;
update mangos_string set content_default='帐户 %s 不产生了 (未知者错误)' where entry=1008;
update mangos_string set content_default='玩家 %s(Guid: %u) 帐户 %s(ID: %u) 划除。' where entry=1009;
update mangos_string set content_default='-==================================================================-' where entry=1012;
update mangos_string set content_default='|<Error>        | %20s |<Error>          |<Er>| <Error>   |' where entry=1011;
update mangos_string set content_default='-[         帐户][   Character][             IP][Map][Zone][Exp][GMLev]-' where entry=1010;
update mangos_string set content_default='没有在线玩家。' where entry=1014;
update mangos_string set content_default='帐户 %s(ID: %u) 最多有 %u 扩充现在允许了。' where entry=1100;
update mangos_string set content_default='那天的信息换成: %s' where entry=1101;
update mangos_string set content_default='信息送了到 %s: %s' where entry=1102;
update mangos_string set content_default='%d - %s %s' where entry=1103;
update mangos_string set content_default='%d - %s' where entry=1104;
update mangos_string set content_default='%d - %s' where entry=1105;
update mangos_string set content_default='%d - %s %s' where entry=1106;
update mangos_string set content_default='%d - %s' where entry=1107;
update mangos_string set content_default='%d - %s %s' where entry=1108;
update mangos_string set content_default='%d - %s %s %s %s' where entry=1109;
update mangos_string set content_default='%d - %s X:%f Y:%f Z:%f MapId:%d' where entry=1110;
update mangos_string set content_default='%d - %s X:%f Y:%f Z:%f MapId:%d' where entry=1111;
update mangos_string set content_default='失败的对开着的文件: %s' where entry=1112;
update mangos_string set content_default='帐户 %s(%u) 有最大数量允许了角色 (客户界限)' where entry=1113;
update mangos_string set content_default='垃圾场文件有坏掉的数据!' where entry=1114;
update mangos_string set content_default='病人角色名字!' where entry=1115;
update mangos_string set content_default='病人角色 guid!' where entry=1116;
update mangos_string set content_default='角色 guid%在使用中的 u!' where entry=1117;
update mangos_string set content_default='%d- 公会: %s(guid: %u) %s' where entry=1118;
update mangos_string set content_default='你必须使用男性或如性的女性。' where entry=1119;
update mangos_string set content_default='你变化性别 %s 到 %s。' where entry=1120;
update mangos_string set content_default='你的性别换成 %s 被 %s。' where entry=1121;
update mangos_string set content_default='(%u/%u+ 烫发 %u+ 临时雇员 %u)' where entry=1122;
update mangos_string set content_default='不是伴侣动物发现' where entry=1123;
update mangos_string set content_default='错误的伴侣动物类型' where entry=1124;
update mangos_string set content_default='你的伴侣动物有学问的所有人才' where entry=1125;
update mangos_string set content_default='你的伴侣动物人才有是重新设置。' where entry=1126;
update mangos_string set content_default='人才 %s 伴侣动物重新设置。' where entry=1127;
update mangos_string set content_default='%d- |cffffffff| Htaxinode:%u| h[%s% s]|h| r(地图:%u X:%f Y:%f Z:%f)' where entry=1128;
update mangos_string set content_default='%d- %s% s(地图:%u X:%f Y:%f Z:%f)' where entry=1129;
update mangos_string set content_default='你对视野 cinemitic 的尝试 %u 但是它不存在。' where entry=1200;
update mangos_string set content_default='你对视野电影的尝试 %u 但是它不存在。' where entry=1201;
update mangos_string set content_default='联盟' where entry=1300;
update mangos_string set content_default='部落' where entry=1301;
update mangos_string set content_default='%s被%s摧毁了！' where entry=1302;
update mangos_string set content_default='%s正在遭受攻击！如不采取行动，%s将摧毁它！' where entry=1303;
update mangos_string set content_default='%s被%s占领了！' where entry=1304;
update mangos_string set content_default='%s被%s占领了！' where entry=1305;
update mangos_string set content_default='%s被%s占领了！' where entry=1306;
update mangos_string set content_default='%s正在遭受攻击！如不采取行动，%s将夺取它！' where entry=1307;
update mangos_string set content_default='%s已夺取%s！矿洞中的资源将补充其战力！' where entry=1308;
update mangos_string set content_default='深铁矿洞' where entry=1309;
update mangos_string set content_default='冷齿矿洞' where entry=1310;
update mangos_string set content_default='雷矛急救站' where entry=1311;
update mangos_string set content_default='丹巴达尔南部碉堡' where entry=1312;
update mangos_string set content_default='丹巴达尔北部碉堡' where entry=1313;
update mangos_string set content_default='雷矛墓地' where entry=1314;
update mangos_string set content_default='冰翼碉堡' where entry=1315;
update mangos_string set content_default='石炉墓地' where entry=1316;
update mangos_string set content_default='石炉碉堡' where entry=1317;
update mangos_string set content_default='雪落墓地' where entry=1318;
update mangos_string set content_default='冰雪哨塔' where entry=1319;
update mangos_string set content_default='冰雪墓地' where entry=1320;
update mangos_string set content_default='哨塔高地' where entry=1321;
update mangos_string set content_default='霜狼墓地' where entry=1322;
update mangos_string set content_default='东部霜狼哨塔' where entry=1323;
update mangos_string set content_default='西部霜狼哨塔' where entry=1324;
update mangos_string set content_default='霜狼救援所' where entry=1325;
update mangos_string set content_default='奥特兰克山谷的战斗将于1分钟后开始。' where entry=1326;
update mangos_string set content_default='奥特兰克山谷的战斗将于30秒后开始。做好准备！' where entry=1327;
update mangos_string set content_default='奥特兰克山谷的战斗开始了！' where entry=1328;
update mangos_string set content_default='联盟的战力即将耗尽！' where entry=1329;
update mangos_string set content_default='部落的战力即将耗尽！' where entry=1330;
update mangos_string set content_default='霜狼的将军被杀死了！' where entry=1331;
update mangos_string set content_default='部落的将军被杀死了！' where entry=1332;
update mangos_string set content_default='奥特兰克山谷的战斗将于2分钟后开始。' where entry=1333;
update mangos_string set content_default='|cff00ff00新加入|r|cffff00ff %s.|r |cff00ff00进入:|r|cffff00ff %d.|r' where entry=2000;
update mangos_string set content_default='|cff00ff00人物|r|cffff00ff %s |r|cff00ff00编辑/进入:|r|cffff00ff %d.|r' where entry=2001;
update mangos_string set content_default='|cff00ff00人物|r|cffff00ff %s |r|cff00ff00进入被删除/拒绝:|r|cffff00ff %d.|r' where entry=2002;
update mangos_string set content_default='|cff00ff00关闭|r:|cff00ccff %s|r' where entry=2003;
update mangos_string set content_default='|cff00ff00删除|r:|cff00ccff %s|r' where entry=2004;
update mangos_string set content_default='不符合进入.' where entry=2005;
update mangos_string set content_default='关闭中..请结束.' where entry=2006;
update mangos_string set content_default='进入 %d 已经被配置.' where entry=2007;
update mangos_string set content_default='%u 已被重新加入.' where entry=2008;
update mangos_string set content_default='显示已进入名单.' where entry=2009;
update mangos_string set content_default='显示在线进入名单.' where entry=2010;
update mangos_string set content_default='显示未进入表列.' where entry=2011;
update mangos_string set content_default='指明了无效的名称。名称应该是一个在线的游戏中GM.' where entry=2012;
update mangos_string set content_default='已经被配置给自己。取消使用。取消配置改由 %d 配置.' where entry=2013;
update mangos_string set content_default='％d 未配置，你不能指定配置.' where entry=2014;
update mangos_string set content_default='与比自己更高的安全级别，你不能由工作人员配置.' where entry=2015;
update mangos_string set content_default='是 GM %d, 你不能结束 GM.' where entry=2016;
update mangos_string set content_default='|cff00ff00GM 评论|r: [%s]|r' where entry=2023;
update mangos_string set content_default='|cff00ff00创建者|r:|cff00ccff %s|r' where entry=2018;
update mangos_string set content_default='|cff00ff00最后一个改变者|r:|cff00ccff %s ago|r' where entry=2019;
update mangos_string set content_default='|cff00ff00配置者|r:|cff00ccff %s|r' where entry=2020;
update mangos_string set content_default='|cff00ff00未配置|r:|cff00ccff %s|r' where entry=2021;
update mangos_string set content_default='|cff00ff00进入消息|r: [%s]|r' where entry=2022;
update mangos_string set content_default='|cffaaffaa进入|r:|cffaaccff %d.|r' where entry=2017;
update mangos_string set content_default='|cff00ff00创建时间|r:|cff00ccff %s ago|r' where entry=2025;
update mangos_string set content_default='你冻结了玩家 %s.' where entry=5000;
update mangos_string set content_default='这可能是有趣的，但没有...你不能冻结自己!' where entry=5001;
update mangos_string set content_default='无效的输入检查目标的名称.' where entry=5002;
update mangos_string set content_default='你解冻玩家 %s.' where entry=5003;
update mangos_string set content_default='当前没有冻结玩家.' where entry=5004;
update mangos_string set content_default='以下玩家被冻结在服务器名单上:' where entry=5005;
update mangos_string set content_default='- %s' where entry=5006;
update mangos_string set content_default='你必须在一个团队中才能进入此副本.' where entry=5007;
update mangos_string set content_default='开始在服务器播放音乐: %u' where entry=5009;
update mangos_string set content_default='链接GUID: %u, 输入: %u (%s)' where entry=5010;
update mangos_string set content_default='你可以瞬间移动自己!' where entry=5011;
update mangos_string set content_default='没有找到地图!' where entry=5012;
update mangos_string set content_default='[世界]' where entry=5013;
update mangos_string set content_default='[实例]' where entry=5014;
update mangos_string set content_default='[战场]' where entry=5015;
update mangos_string set content_default='[竞技场]' where entry=5016;
update mangos_string set content_default='[副本重置时间: %s]' where entry=5017;
update mangos_string set content_default='|cfff00000[GM Announcement]: %s|r' where entry=6613;
update mangos_string set content_default='Notification to GM''s - ' where entry=6614;
update mangos_string set content_default='|cffffff00[|c1f40af20GM 公告|r |cffff0000%s|cffffff00]:|r %s|r' where entry=6615;
update mangos_string set content_default='静音ON %s' where entry=6616;
update mangos_string set content_default='WORLD: 拒绝连接.' where entry=7523;
update mangos_string set content_default='WORLD: 接受连接.' where entry=7524;
update mangos_string set content_default='部落占领了了望台！' where entry=10001;
update mangos_string set content_default='联盟占领了了望台！' where entry=10002;
update mangos_string set content_default='部落占领了竞赛场！' where entry=10003;
update mangos_string set content_default='联盟占领的竞赛场！' where entry=10004;
update mangos_string set content_default='部落占领了碎石岭！' where entry=10005;
update mangos_string set content_default='联盟占领的碎石岭！' where entry=10006;
update mangos_string set content_default='部落失去了了望台的控制权！' where entry=10007;
update mangos_string set content_default='联盟失去了了望台的控制权！' where entry=10008;
update mangos_string set content_default='部落失去了竞赛场的控制权！' where entry=10009;
update mangos_string set content_default='联盟失去了竞赛场的控制权！' where entry=10010;
update mangos_string set content_default='部落失去了碎石岭的控制权！' where entry=10011;
update mangos_string set content_default='联盟失去了碎石岭的控制权！' where entry=10012;
update mangos_string set content_default='部落占领了西部灯塔！' where entry=10013;
update mangos_string set content_default='联盟占领了西部灯塔！' where entry=10014;
update mangos_string set content_default='部落占领了东部灯塔！' where entry=10015;
update mangos_string set content_default='联盟占领了西部灯塔！' where entry=10016;
update mangos_string set content_default='部落占领了双塔墓地！' where entry=10017;
update mangos_string set content_default='联盟占领了双塔墓地！' where entry=10018;
update mangos_string set content_default='部落失去了西部灯塔的控制权！' where entry=10019;
update mangos_string set content_default='联盟失去了西部灯塔的控制权！' where entry=10020;
update mangos_string set content_default='部落失去了东部灯塔的控制权！' where entry=10021;
update mangos_string set content_default='联盟失去了东部灯塔的控制权！' where entry=10022;
update mangos_string set content_default='部落失去了双塔墓地的控制权！' where entry=10023;
update mangos_string set content_default='联盟失去了双塔墓地的控制权！' where entry=10024;
update mangos_string set content_default='部落已夺得哈兰的控制权！' where entry=10025;
update mangos_string set content_default='联盟已夺得哈兰的控制权！' where entry=10026;
update mangos_string set content_default='部落失去了哈兰的控制权！' where entry=10027;
update mangos_string set content_default='联盟失去了哈兰的控制权！' where entry=10028;
update mangos_string set content_default='部落占领了一座灵魂塔！' where entry=10029;
update mangos_string set content_default='联盟占领了一座灵魂塔！' where entry=10030;
update mangos_string set content_default='部落失去了一座灵魂塔！' where entry=10031;
update mangos_string set content_default='联盟失去了一座灵魂塔！' where entry=10032;
update mangos_string set content_default='部落占领了北地哨塔！' where entry=10033;
update mangos_string set content_default='联盟占领了北地哨塔！' where entry=10034;
update mangos_string set content_default='部落占领了东墙哨塔！' where entry=10035;
update mangos_string set content_default='联盟占领了东墙哨塔！' where entry=10036;
update mangos_string set content_default='部落占领了皇冠哨塔！' where entry=10037;
update mangos_string set content_default='联盟占领了皇冠哨塔！' where entry=10038;
update mangos_string set content_default='部落占领了病木林哨塔！' where entry=10039;
update mangos_string set content_default='联盟占领了病木林哨塔！' where entry=10040;
update mangos_string set content_default='部落失去了北地哨塔的控制权！' where entry=10041;
update mangos_string set content_default='联盟失去了北地哨塔的控制权！' where entry=10042;
update mangos_string set content_default='部落失去了东墙哨塔的控制权！' where entry=10043;
update mangos_string set content_default='联盟失去了东墙哨塔的控制权！' where entry=10044;
update mangos_string set content_default='部落失去了皇冠哨塔的控制权！' where entry=10045;
update mangos_string set content_default='联盟失去了皇冠哨塔的控制权！' where entry=10046;
update mangos_string set content_default='部落失去了病木林哨塔的控制权！' where entry=10047;
update mangos_string set content_default='联盟失去了病木林哨塔的控制权！' where entry=10048;
update mangos_string set content_default='The Horde has collected 200 silithyst!' where entry=10049;
update mangos_string set content_default='The Alliance has collected 200 silithyst!' where entry=10050;
update mangos_string set content_default='带我去北地哨塔。' where entry=10051;
update mangos_string set content_default='带我去东墙哨塔。' where entry=10052;
update mangos_string set content_default='带我去皇冠哨塔。' where entry=10053;
update mangos_string set content_default='将旗帜给我，我将为了联盟的荣耀将它带至中心灯塔！' where entry=10054;
update mangos_string set content_default='将旗帜给我，我将为了部落的荣耀将它带至中心灯塔！' where entry=10055;
update mangos_string set content_default='|cffffff00[|c00077766自动发布信息|cffffff00]: |cFFF222FF%s|r' where entry=11000;
update mangos_string set content_default='您还没有选择-1(或)你是当前本地的权限.' where entry=11001;
update mangos_string set content_default='第一: %u' where entry=5020;
update mangos_string set content_default='护甲: %u' where entry=5021;
update mangos_string set content_default='泰坦大门已经被联盟占领!' where entry=10063;
update mangos_string set content_default='泰坦大门已经被部落占领!' where entry=10064;
update mangos_string set content_default='%s 已经被破坏了!' where entry=10061;
update mangos_string set content_default='第一回合-  完成!' where entry=10062;
update mangos_string set content_default='远古海滩战斗打开!勇士们.为了我们的荣耀，冲！' where entry=10059;
update mangos_string set content_default='%s 受到攻击!' where entry=10060;
update mangos_string set content_default='远古海滩战场将在30秒内打开!请各位玩家准备好.' where entry=10058;
update mangos_string set content_default='远古海滩战场将在2分钟内打开!' where entry=10056;
update mangos_string set content_default='远古海滩战场将在1分钟内打开!' where entry=10057;
update mangos_string set content_default='给与第一个加入频道的玩家频道管理权"%s": 启用' where entry=5022;
update mangos_string set content_default='这个是关闭着的.' where entry=5008;
update mangos_string set content_default='编码: %u' where entry=5024;
update mangos_string set content_default='类型: %u' where entry=5025;
update mangos_string set content_default='外观编码: %u' where entry=5026;
update mangos_string set content_default='名称: %s' where entry=5027;
update mangos_string set content_default='你不能说(喊)或表情动作，直到你等级达到 %d.' where entry=6604;
update mangos_string set content_default='你不能使用密语，直到你等级达到 %d.' where entry=6605;
update mangos_string set content_default='您不能进入，直到你成为级别 %d.' where entry=6606;
update mangos_string set content_default='您不能使用拍卖功能，直到你等级达到 %d.' where entry=6607;
update mangos_string set content_default='你可以进入，直到你等级达到 %d.' where entry=6608;
update mangos_string set content_default='你不能交易??，直到你等级达到 %d.' where entry=6609;
update mangos_string set content_default='您级别小于 %d不能使用交易.' where entry=6610;
update mangos_string set content_default='你不能发送邮件直到你等级达到%d.' where entry=6611;
update mangos_string set content_default='级别小于 %d 你不能传送邮件.' where entry=6612;
update mangos_string set content_default='|cff00ccff%s|r |cff00ff00添加注释|r: [%s]|r' where entry=2024;
update mangos_string set content_default='-[%16s][%12s][%15s][%3d][%4d][%d][%d]-' where entry=1013;
update mangos_string set content_default='二手的不完全键入摆脱指令, 需要类型它完全 (摆脱), 或指令二手的不在 RA 指令线。' where entry=1015;
update mangos_string set content_default='战场已被禁用，不能加入队列。' where entry=747;
update mangos_string set content_default='竞技场已被禁用，不能加入队列。' where entry=748;
update mangos_string set content_default='物品 ''%i'' 已经在商人的清单里存在了.' where entry=210;
update mangos_string set content_default='输入 %u 未发现 creature_template 表.' where entry=817;
update mangos_string set content_default='输入 %u 没有发现sCreatureStorage。可能出现的新线在creature_template，但不重新引导的情况下，你不能添加新的生物。只有修改是允许的。' where entry=818;
update mangos_string set content_default='第二回合将在1分钟后开始。' where entry=10065;
update mangos_string set content_default='第二回合将在30秒后开始，做好准备！' where entry=10066;
update mangos_string set content_default='大门已被攻破！泰坦圣物危急！' where entry=10067;
update mangos_string set content_default='联盟占领了南部墓地！' where entry=10068;
update mangos_string set content_default='联盟占领了西部墓地！' where entry=10069;
update mangos_string set content_default='联盟占领了东部墓地！' where entry=10070;
update mangos_string set content_default='部落占领了南部墓地！' where entry=10071;
update mangos_string set content_default='部落占领了西部墓地！' where entry=10072;
update mangos_string set content_default='部落占领了东部墓地！' where entry=10073;
update mangos_string set content_default='口令:' where entry=62;
update mangos_string set content_default='| GUID       | Name                 | 帐户                      | Delete Date         |' where entry=1016;
update mangos_string set content_default='| %10u | %20s | %15s (%10u) | %19s |' where entry=1017;
update mangos_string set content_default='错误：510' where entry=1018;
update mangos_string set content_default='没找到角色.' where entry=1019;
update mangos_string set content_default='撤消了文字数据 :' where entry=1020;
update mangos_string set content_default='删除了文字数据 :' where entry=1021;
update mangos_string set content_default='错误: 您只能指定一个新的名字，你不能只选择单一个字！' where entry=1022;
update mangos_string set content_default='文字 ''%s'' (GUID: %u 帐户 %u) can''t be 恢复：帐号不存在！' where entry=1023;
update mangos_string set content_default='文字 ''%s'' (GUID: %u 帐户 %u) can''t be 恢复：帐户的文字清单!' where entry=1024;
update mangos_string set content_default='文字 ''%s'' (GUID: %u 帐户 %u) can''t be 恢复：新名称已经使用！' where entry=1025;
update mangos_string set content_default='GUID: %u Name: %s 帐户: %s (%u) 日期: %s' where entry=1026;
update mangos_string set content_default='战利品ID: %u' where entry=5028;
update mangos_string set content_default='事件开始 %u"% s"' where entry=1130;
update mangos_string set content_default='结果达到了极限 (最大结果: %d)' where entry=5029;
update mangos_string set content_default='事件停止 %u"% s"' where entry=1131;
update mangos_string set content_default='跟随玩家 %s (lowguid %u)' where entry=1132;
update mangos_string set content_default='跟随生物 %s (lowguid %u)' where entry=1133;
update mangos_string set content_default='本地触发侦错打开 on.' where entry=1202;
update mangos_string set content_default='本地触发侦错打开 off.' where entry=1203;
update mangos_string set content_default='你已经达到 %u.' where entry=1204;
update mangos_string set content_default='城市' where entry=819;
update mangos_string set content_default='%s 的求助!' where entry=5035;
update mangos_string set content_default='跟随 <NULL>' where entry=1134;
update mangos_string set content_default='列出已已学天赋:' where entry=1135;
update mangos_string set content_default='SQL 驱动程序启用查询日志.' where entry=1027;
update mangos_string set content_default='SQL 禁用驱动程序查询记录.' where entry=1028;
update mangos_string set content_default='给与第一个加入频道的玩家频道管理权"%s": 禁用' where entry=5023;
update mangos_string set content_default='|cff00ff00进入响应|r: [%s]|r' where entry=2029;
update mangos_string set content_default='本次战斗将在2分钟内开始.' where entry=1205;
update mangos_string set content_default='本次战斗将在1分钟内开始.' where entry=1206;
update mangos_string set content_default='战斗开始了！' where entry=1208;
update mangos_string set content_default='本次战斗将在30秒内开始!' where entry=1207;
update mangos_string set content_default='已被联盟占领' where entry=1209;
update mangos_string set content_default='已被部落占领' where entry=1210;
update mangos_string set content_default='%s 赢得了胜利!' where entry=1211;
update mangos_string set content_default='西大门 %s 被破坏!' where entry=1212;
update mangos_string set content_default='东侧%s已被摧毁！' where entry=1213;
update mangos_string set content_default='南侧%s已被摧毁！' where entry=1214;
update mangos_string set content_default='北侧%s已被摧毁！' where entry=1215;
update mangos_string set content_default='$n突袭了%s！' where entry=1216;
update mangos_string set content_default='$n守住了%s！' where entry=1217;
update mangos_string set content_default='$n突袭了%s！如不采取行动，%s将在1分钟内控制它！' where entry=1218;
update mangos_string set content_default='%s占领了%s！' where entry=1219;
update mangos_string set content_default='车间' where entry=1220;
update mangos_string set content_default='码头' where entry=1221;
update mangos_string set content_default='精炼厂' where entry=1222;
update mangos_string set content_default='矿厂' where entry=1223;
update mangos_string set content_default='机场' where entry=1224;
update mangos_string set content_default='附近生物 (距离 %f): %u' where entry=556;
update mangos_string set content_default='你已禁言%s，时长%u分钟，下次登录生效。原因: %s.' where entry=283;
update mangos_string set content_default='你的闲谈将被关闭 %u 分钟。' where entry=300;
update mangos_string set content_default='a”? 地图: %s, Area: %s, Zone: %s' where entry=848;
update mangos_string set content_default='(找到天赋: %u 已使用天赋点: %u)' where entry=1136;
update mangos_string set content_default='%s充满恐惧地想要转身逃跑！' where entry=5030;
update mangos_string set content_default='开发模式 ON' where entry=1137;
update mangos_string set content_default='开发模式 OFF' where entry=1138;
update mangos_string set content_default='准备关闭 - 请等待进入' where entry=2027;
update mangos_string set content_default='即将关闭 - 计数器已重置 |cffff00ff 1|r' where entry=2028;
update mangos_string set content_default='AI名称: %s 脚本名称: %s' where entry=5031;
update mangos_string set content_default='按照玩家的％s（ ü lowguid ％ ）' where entry=1139;
update mangos_string set content_default='按照生物％s的（ lowguid ％U ）' where entry=1140;
update mangos_string set content_default='按照<NULL> “' where entry=1141;
update mangos_string set content_default='效果动作' where entry=1142;
update mangos_string set content_default='目标moveFlags ： ％ U ， moveFlagsExtra的： ％u个。' where entry=1143;
update mangos_string set content_default='设置目标的moveFlags ％ U ， moveFlagsExtra的： ％U' where entry=1144;
update mangos_string set content_default='没有找到战场！' where entry=5032;
update mangos_string set content_default='发现没有成就标准！' where entry=5033;
update mangos_string set content_default='没有户外PvP发现！' where entry=5034;
update mangos_string set content_default='％s的％ s已被抓获' where entry=12050;
update mangos_string set content_default='由％s ％ s是攻击' where entry=12051;
update mangos_string set content_default='残破的庙攻城车间' where entry=12052;
update mangos_string set content_default='东园胜利攻城车间' where entry=12053;
update mangos_string set content_default='西园胜利攻城车间' where entry=12054;
update mangos_string set content_default='沉没之环攻城车间' where entry=12055;
update mangos_string set content_default='联盟' where entry=12057;
update mangos_string set content_default='部落' where entry=12056;
update mangos_string set content_default='冬拥湖的战斗即将开始！' where entry=12058;
update mangos_string set content_default='您已达到1级：下士' where entry=12059;
update mangos_string set content_default='您已达到等级2：中尉' where entry=12060;
update mangos_string set content_default='东南部守塔' where entry=12061;
update mangos_string set content_default='东北保持塔' where entry=12062;
update mangos_string set content_default='西南部保持塔' where entry=12063;
update mangos_string set content_default='西北部保持塔' where entry=12064;
update mangos_string set content_default='％ s已经损坏！' where entry=12065;
update mangos_string set content_default='％ s已经被摧毁了！' where entry=12066;
update mangos_string set content_default='冬拥湖的战斗开始了！' where entry=12067;
update mangos_string set content_default='％ s已经成功地扞卫了冬拥湖要塞！' where entry=12068;
update mangos_string set content_default='南部的塔' where entry=12069;
update mangos_string set content_default='东塔' where entry=12070;
update mangos_string set content_default='西部塔' where entry=12071;
update mangos_string set content_default='冬拥湖堡垒已被抓获由％s ！' where entry=12072;
update mangos_string set content_default='作弊指令状态：' where entry=357;
update mangos_string set content_default='执法者 ： ％S 。' where entry=358;
update mangos_string set content_default='施法时间： ％S 。' where entry=359;
update mangos_string set content_default='冷却： ％S 。' where entry=360;
update mangos_string set content_default='功率： ％S 。' where entry=361;
update mangos_string set content_default='水上行走: %s.' where entry=362;
update mangos_string set content_default='玩家名称： ％ S，州： ％S ，牢狱％ U（ ％ ） ，角色：％ S，注释：％S' where entry=9980;
update mangos_string set content_default='LfgGroup ：％ U，状态： ％s的，地牢： ％U' where entry=9981;
update mangos_string set content_default='不在组中' where entry=9982;
update mangos_string set content_default='队列清除' where entry=9983;
update mangos_string set content_default='LFG选项： ％U' where entry=9984;
update mangos_string set content_default='LFG选项改变' where entry=9985;
update mangos_string set content_default='无' where entry=9986;
update mangos_string set content_default='角色检查' where entry=9987;
update mangos_string set content_default='排队' where entry=9988;
update mangos_string set content_default='推荐' where entry=9989;
update mangos_string set content_default='投票踢人' where entry=9990;
update mangos_string set content_default='在地牢' where entry=9991;
update mangos_string set content_default='成品地牢' where entry=9992;
update mangos_string set content_default='RAID浏览器' where entry=9993;
update mangos_string set content_default='坦克' where entry=9994;
update mangos_string set content_default='小灵' where entry=9995;
update mangos_string set content_default='Dps的' where entry=9996;
update mangos_string set content_default='领导者' where entry=9997;
update mangos_string set content_default='无' where entry=9998;
update mangos_string set content_default='错误' where entry=9999;
update mangos_string set content_default='*有八卦（ ％U ）' where entry=820;
update mangos_string set content_default='*任务给予者（ ％U ）' where entry=821;
update mangos_string set content_default='*一流的教练（ ％U ）' where entry=822;
update mangos_string set content_default='*专业教练（ ％U ）' where entry=823;
update mangos_string set content_default='*弹药供应商（ ％U ）' where entry=824;
update mangos_string set content_default='*是食品供应商（ ％U ）' where entry=825;
update mangos_string set content_default='*是毒药供应商（ ％U ）' where entry=826;
update mangos_string set content_default='*试剂供应商（ ％U ）' where entry=827;
update mangos_string set content_default='*可以修复（ ％U ）' where entry=828;
update mangos_string set content_default='*是飞行高手（ ％U ）' where entry=829;
update mangos_string set content_default='*精神治疗师（ ％U ）' where entry=830;
update mangos_string set content_default='*精神指南（ ％U ）' where entry=831;
update mangos_string set content_default='*旅馆老板（ ％U ）' where entry=832;
update mangos_string set content_default='*银行家（ ％U ）' where entry=833;
update mangos_string set content_default='*请愿（ ％U ）' where entry=834;
update mangos_string set content_default='*战袍设计师（ ％U ）' where entry=835;
update mangos_string set content_default='*战斗大师（ ％U ）' where entry=836;
update mangos_string set content_default='*拍卖（ ％U ）' where entry=837;
update mangos_string set content_default='*是稳定的主（ ％U ）' where entry=838;
update mangos_string set content_default='*公会银行家（ ％U ）' where entry=839;
update mangos_string set content_default='*拼写点击（ ％U ）' where entry=840;
update mangos_string set content_default='*信箱（ ％U ）' where entry=841;
update mangos_string set content_default='*球员车辆（ ％U ）' where entry=842;
update mangos_string set content_default='％ s已经在一组！' where entry=1145;
update mangos_string set content_default='％s的加入％s的组。' where entry=1146;
update mangos_string set content_default='％ s是不是在一组！' where entry=1147;
update mangos_string set content_default='集团是满的！' where entry=1148;
update mangos_string set content_default='产品名称： ％ S（ ％ ） ， GUID ：％ U，标志： ％s的角色：％S' where entry=1150;
update mangos_string set content_default='组类型：％S' where entry=1149;
update mangos_string set content_default='参数错误ID：％ U，不存在' where entry=63;
update mangos_string set content_default='错误的参数不同阵营数：％d' where entry=64;
update mangos_string set content_default='Server: %s has banned %s permanetly, reason: %s' where entry=11007;
update mangos_string set content_default='Server: %s has banned %s for %s, reason: %s' where entry=11006;
update mangos_string set content_default='空清单' where entry=70;
update mangos_string set content_default='- %u (%s)' where entry=71;
update mangos_string set content_default='Server: %s has banned character %s permanetly, reason: %s' where entry=11005;
update mangos_string set content_default='Server: %s has banned character %s for %s, reason: %s' where entry=11004;
update mangos_string set content_default='Server: %s has muted %s for %u minutes, reason: %s' where entry=11003;
update mangos_string set content_default='These aren''t Shango''s tracks.' where entry=28635;
update mangos_string set content_default='Server: %s has kicked %s, reason: %s' where entry=11002;
update mangos_string set content_default='These tracks must belong to Shango.' where entry=28634;
update mangos_string set content_default='帐户％U组（％ ） ：' where entry=69;
update mangos_string set content_default='不能''t 授予角色 %u (%s) 不同阵营 %d. 帐户 %u (%s) 已拥有该角色' where entry=72;
update mangos_string set content_default='不能''t 授予角色 %u (%s) 不同阵营 %d. 帐户 %u (%s) 这个角色不在清单中' where entry=73;
update mangos_string set content_default='授予角色 %u (%s) 不同阵营 %d 的帐户 %u (%s)' where entry=74;
update mangos_string set content_default='不能''t 被拒绝的角色 %u (%s) 不同阵营 %d. 帐户 %u (%s) 已拥有该角色' where entry=75;
update mangos_string set content_default='不能''t 被拒绝的角色 %u (%s) 不同阵营 %d. 帐户 %u (%s) 这个角色不在清单中' where entry=76;
update mangos_string set content_default='被拒绝的角色 %u (%s) 不同阵营 %d 的帐户 %u (%s)' where entry=77;
update mangos_string set content_default='被拒绝的角色 %u (%s) 不同阵营 %d 的帐户 %u (%s)' where entry=78;
update mangos_string set content_default='不能''t 撤销角色 %u (%s) 不同阵营 %d. 帐户 %u (%s) 不具备这个角色' where entry=79;
update mangos_string set content_default='不能添加组％U （％ ） 不同阵营的％D 。帐户％ U（ ％ ）已经有组' where entry=65;
update mangos_string set content_default='不能删除组％U （％ ） 不同阵营的％D 。帐户％ U（ ％ ）不具有该组' where entry=66;
update mangos_string set content_default='帐户 %u (%s) 全部权限:' where entry=92;
update mangos_string set content_default='添加组％U （％ ） 不同阵营的帐户％U ％D （％S ）' where entry=67;
update mangos_string set content_default='删除组％U （％ ） 不同阵营的帐户％ U（ ％s的％D ）' where entry=68;
update mangos_string set content_default='a”? 金钱: %ug%us%uc' where entry=847;
update mangos_string set content_default='设备ID: %u (原: %u).' where entry=5036;
update mangos_string set content_default='玩家 %s 不能使用密语.' where entry=363;
update mangos_string set content_default='邮件消息: # of 邮件: %u, 玩家: %s(%u)' where entry=1151;
update mangos_string set content_default='邮件名称: %u 标题: "%s" 钱: %ug%us%uc' where entry=1152;
update mangos_string set content_default='发件人: %s(%u), 接收: %s(%u)' where entry=1153;
update mangos_string set content_default='有效时间: %s, 到期时间: %s' where entry=1154;
update mangos_string set content_default='项目 %s[输入:%u 指南:%u 统计:%u]' where entry=1155;
update mangos_string set content_default='邮件信息：没有邮件。' where entry=1156;
update mangos_string set content_default='传送到沉没之环墓地。' where entry=20071;
update mangos_string set content_default='传送到破碎圣殿墓地.' where entry=20072;
update mangos_string set content_default='传送到东园墓地。' where entry=20074;
update mangos_string set content_default='传送到西园墓地.' where entry=20073;
update mangos_string set content_default='传送到要塞墓地.' where entry=20070;
update mangos_string set content_default='传送到部落营区.' where entry=20075;
update mangos_string set content_default='传送到联盟营区.' where entry=20076;
update mangos_string set content_default='冬拥湖队列中。' where entry=20077;
update mangos_string set content_default='公会名称 ''%s'' 已被使用' where entry=96;
update mangos_string set content_default='更改公会名称 ''%s'' to ''%s''' where entry=97;
update mangos_string set content_default='''%s'' 名称已经存在，请另外选择一个' where entry=98;
update mangos_string set content_default='玩家 ''%s'' 更换名称 ''%s''' where entry=99;
update mangos_string set content_default='这个名称不能使用，请另外选择一个' where entry=167;
update mangos_string set content_default='无效的游戏物体类型，必须是一个可破坏的建筑物。' where entry=176;
update mangos_string set content_default='游戏的对象 %s (GUID: %u) 损坏 %u (实际: %u).' where entry=177;
update mangos_string set content_default='a”? 等级: %u (%u/%u XP (%u XP left))' where entry=843;
update mangos_string set content_default='a”? 最后 IP: %s (锁定: %s)' where entry=752;
update mangos_string set content_default='公会: %s (%u) 排名: %s 附注: %s 关闭附注: %s' where entry=749;
update mangos_string set content_default='??é Last Login: %s (Failed Logins: %u)' where entry=716;
update mangos_string set content_default='??é Account: %s (ID: %u), GMLevel: %u' where entry=714;
update mangos_string set content_default='指令帮助：指令 .pinfo 不支持  ''rep'' 选择,玩家不在线.' where entry=550;
update mangos_string set content_default='已登录时间: %s 等级: %u 金钱: %ug%us%uc' where entry=549;
update mangos_string set content_default='玩家%s %s (guid: %u) 帐号: %s (id: %u) G M等级: %u 最后IP: %s 最后登陆: %s Latency: %ums' where entry=548;
update mangos_string set content_default='男性' where entry=855;
update mangos_string set content_default='女性' where entry=856;
update mangos_string set content_default='竞技场队伍 [%u] not found' where entry=857;
update mangos_string set content_default='已经有一个竞技场队伍命名 "%s"' where entry=858;
update mangos_string set content_default='已在 %s 竞技场队伍' where entry=859;
update mangos_string set content_default='竞技场队伍在战斗中' where entry=860;
update mangos_string set content_default='竞技场名称: "%s" 没有找到或类似的' where entry=861;
update mangos_string set content_default='[%s] 不是队伍成员 "%s"' where entry=862;
update mangos_string set content_default='[%s] 已经在队伍中 "%s"' where entry=863;
update mangos_string set content_default='创建新的竞技场队伍 [Name: "%s"][Id: %u][Type: %u][Captain GUID: %u]' where entry=864;
update mangos_string set content_default='竞技场队伍名称: "%s"[Id: %u] 解散' where entry=865;
update mangos_string set content_default='竞技场队伍 [Id: %u] change from "%s" to "%s"' where entry=866;
update mangos_string set content_default='竞技场队伍名称: "%s"[Id: %u] change capitan from[%s] to [%s]' where entry=867;
update mangos_string set content_default='竞技场队伍: "%s"[%u] - Rating: %u - Type: %ux%u' where entry=868;
update mangos_string set content_default='名称:"%s"[guid:%u] - PR: %u - %s' where entry=869;
update mangos_string set content_default='|"%s"[ID:%u](%ux%u)|' where entry=870;
update mangos_string set content_default='潘基剩下时间： ％S ，取缔： ％S ，原因：％' where entry=453;
update mangos_string set content_default='MechanicImmuneMask: %u' where entry=5037;
update mangos_string set content_default='Unit Flags: %u' where entry=5038;
update mangos_string set content_default='a”? 公会: %s (ID: %u)' where entry=849;
update mangos_string set content_default='a”?a”€ 排名: %s' where entry=850;
update mangos_string set content_default='a”?a”€ 注释: %s' where entry=851;
update mangos_string set content_default='a”?a”€ O. 注释: %s' where entry=852;
update mangos_string set content_default='a”? 出场时间: %s' where entry=853;
update mangos_string set content_default='a”” 邮件: %d Read/%u Total' where entry=854;
update mangos_string set content_default='a”? 等级: %u' where entry=871;